name: arabicinyourhands
description: Arabic in your hands

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  clipboard: ^0.1.3
  flutter_staggered_animations: ^1.1.1
  wakelock_plus: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.35
  flutter_flip_card: ^0.0.4
  smooth_page_indicator: ^1.1.0
  flutter_colorpicker: ^1.0.3
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/databases/
    - assets/audios/
    - assets/icons/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_light.ttf
    - family: Gilroy medium
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Play
      fonts:
        - asset: assets/fonts/play.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/noto_sans.ttf