name: arabicinyourhands
description: Arabic in your hands

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  path: ^1.9.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  clipboard: ^0.1.3
  flutter_staggered_animations: ^1.1.1
  wakelock_plus: ^1.1.5
  hive_flutter: ^1.1.0
  just_audio: ^0.9.36
  flutter_flip_card: ^0.0.5
  smooth_page_indicator: ^1.1.0
  flutter_material_color_picker: ^1.2.0
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/databases/
    - assets/audios/
    - assets/icons/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Markazi
      fonts:
        - asset: assets/fonts/markazi.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
        - asset: assets/fonts/gilroy_light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic.ttf