name: arabicinyourhands
description: Arabic in your hands

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  provider: ^6.0.1
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  salomon_bottom_bar: ^3.2.0
  flutter_svg: ^1.0.0
  url_launcher: ^6.0.17
  scrollable_positioned_list: ^0.2.3
  flutter_staggered_animations: ^1.0.0
  assets_audio_player: ^3.0.3+6
  wakelock: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/databases/
    - assets/icons/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf
    - family: Markazi
      fonts:
        - asset: assets/fonts/markazi.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
        - asset: assets/fonts/gilroy_bold.ttf
    - family: Play
      fonts:
        - asset: assets/fonts/play.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf