name: arabicinyourhands
description: Arabic in your hands

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  clipboard: ^2.0.2
  flutter_staggered_animations: ^1.1.1
  wakelock_plus: ^1.3.2
  hive_flutter: ^1.1.0
  just_audio: ^0.10.4
  flutter_flip_card: ^0.0.6
  smooth_page_indicator: ^1.2.1
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_gen:
  output: lib/gen/
  synthetic_package: false

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/databases/
    - assets/audios/
    - assets/icons/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Markazi
      fonts:
        - asset: assets/fonts/markazi.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
        - asset: assets/fonts/gilroy_light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic.ttf