name: arabicinyourhands
description: Arabic in your hands

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  salomon_bottom_bar: ^3.3.1
  flutter_svg: ^1.1.4
  url_launcher: ^6.1.5
  share_plus: ^4.0.10+1
  clipboard: ^0.1.3
  flutter_staggered_animations: ^1.0.0
  wakelock: ^0.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.28
  flutter_flip_card: ^0.0.3
  smooth_page_indicator: ^1.0.0+2
  flutter_colorpicker: ^1.0.3
  screenshot: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/audios/
    - assets/databases/
    - assets/icons/

  fonts:
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade.ttf
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/lateef.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_light.ttf
    - family: Gilroy medium
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Play
      fonts:
        - asset: assets/fonts/play.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf